spring:
  server:
    port: 8080
  application:
    name: thymeleaf-demo
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html


pool:
  corePoolSize: 1
  maxPoolSize: 10
  queueCapacity: 5
  keepAliveSeconds: 120
  threadNamePrefix: taskTracker-


#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java

